class Information:
    playable_characters = [
        "Dart Monkey",
        "Tack Shooter",
        "Sniper Monkey",
        "Boomerang Thrower",
        "Ninja Monkey",
        "Bomb Shooter",
        "Ice Monkey",
        "Glue Gunner",
        "Monkey Buccaneer",
        "Monkey Ace",
        "Super Monkey",
        "Monkey Apprentice",
        "Monkey Village",
        "Banana Farm",
        "Mortar Monkey",
        "Dartling Gunner",
        "Spike Factory",
        "Heli Pilot",
        "Monkey Engineer",
        "Bloonchipper",
        "Monkey Sub",
    ]

    maps = [
        ["Monkey Lane", "Beginner"],
        ["Bloom", "Beginner"],
        ["Present Delivery", "Beginner"],
        ["Rabbit Holes", "Beginner"],
        ["Snowy Backyard", "Beginner"],
        ["Sprint Track", "Beginner"],
        ["Express Shipping", "Beginner"],
        ["Checkers", "Beginner"],
        ["Skull Peak", "Beginner"],
        ["Lobby", "Beginner"],
        ["3 Times Around", "Beginner"],
        ["North Pole", "Beginner"],
        ["Patch", "Beginner"],
        ["Fireworks", "Beginner"],
        ["Brick Wall", "Beginner"],
        ["Park Path", "Beginner"],
        ["The Rink", "Beginner"],
        ["Roswell", "Beginner"],
        ["Space Truckin'", "Beginner"],
        ["Z Factor", "Beginner"],
        ["Maze", "Beginner"],
        ["Oasis", "Beginner"],
        ["Snowman", "Beginner"],
        ["Parking Lot", "Beginner"],
        ["Daffodils", "Beginner"],
        ["Dance Floor", "Beginner"],
        ["Bobsleigh Run", "Beginner"],
        ["Six Feet", "Intermediate"],
        ["River Rapids", "Intermediate"],
        ["Workshop", "Intermediate"],
        ["Bloon of Clubs", "Intermediate"],
        ["Archipelago", "Intermediate"],
        ["Bloon Circles", "Intermediate"],
        ["Slalom", "Intermediate"],
        ["Snake River", "Intermediate"],
        ["Dockside", "Intermediate"],
        ["Country Road", "Intermediate"],
        ["Jungle", "Intermediate"],
        ["Ice Flow", "Intermediate"],
        ["Wattle Trees", "Intermediate"],
        ["Pyramids", "Intermediate"],
        ["Dune Sea", "Intermediate"],
        ["Lava Fields", "Intermediate"],
        ["Head In The Clouds", "Intermediate"],
        ["Flooded Lane", "Intermediate"],
        ["Walk in the Park", "Intermediate"],
        ["Ancient Tomb", "Intermediate"],
        ["Village Shore", "Intermediate"],
        ["Trick or Treat", "Intermediate"],
        ["Hearthside", "Intermediate"],
        ["Forgotten Garden", "Intermediate"],
        ["Autumn Leaves", "Intermediate"],
        ["Lonely Heart", "Intermediate"],
        ["Over-Throne", "Intermediate"],
        ["Phase Portals", "Advanced"],
        ["Lightning Scar", "Advanced"],
        ["Switch", "Advanced"],
        ["Mount Magma", "Advanced"],
        ["The Eye", "Advanced"],
        ["U-Turn", "Advanced"],
        ["The Great Divide", "Advanced"],
        ["Water Hazard", "Advanced"],
        ["Rink Revenge", "Advanced"],
        ["Challenger Deep", "Advanced"],
        ["Long Range", "Advanced"],
        ["Battle Knot", "Advanced"],
        ["Candyland", "Advanced"],
        ["Crypt Keeper", "Advanced"],
        ["Scorched Earth", "Advanced"],
        ["Siege", "Advanced"],
        ["Igloos", "Advanced"],
        ["Bigfoot", "Advanced"],
        ["Land's End", "Advanced"],
        ["Tidal Pools", "Advanced"],
        ["Egg Hunt", "Advanced"],
        ["Double Double Cross", "Expert"],
        ["Tunnels", "Expert"],
        ["Castle", "Expert"],
        ["Clock", "Expert"],
        ["Drag Strip", "Expert"],
        ["Death Valley", "Expert"],
        ["Down the Drain", "Expert"],
        ["Treetop", "Expert"],
        ["Runway", "Expert"],
        ["Benguela", "Expert"],
        ["Web", "Expert"],
        ["Forest Path", "Expert"],
        ["Tributaries", "Expert"],
        ["Main Street", "Extreme"],
        ["Bloontonium Lab", "Extreme"],
        ["Tar Pits", "Extreme"],
        ["Campfire", "Extreme"],
        ["Toxic Waste", "Extreme"],
    ]

    difficulties = [
        "Easy",
        "Medium",
        "Hard",
        "Impoppable",
        "Apopalypse",
        "Deflation",
        "Sandbox",
        "Mastery",
    ]
